### ISSUE TITLE
testing with raspberry pi 3

### ISSUE THREAD

**Issue by tahanjokunimi** [besp9510/dma_pwm#1]
Test code starts fine, and I am able to see pulse with oscilloscope.
- but when adjusting the Sleep value bigger and changing frequency, to for example 100 Hz, and Duty % to 50%
       recompiling the code,
       the pulse  is not showing up anymore.
- then if I try to reduce the frequency, for example to 30 Hz,  recompile again.
       pulse is again seen, but it is not 30Hz, but 16,66 Hz at the Oscilloscope.

Any ideas,  why is this happening?  How to test furthermore,  to make Frequencies from 1 to 1000 Hz possible,
                                                         and could it be possible to change code, so that could set pulse length as us values?

Just looking for a solution, to make for example Four independent PWM pulse outputs,
       so that could setup  the  Hz  and  Lenght  values,    as  variables.

**Comment by besp9510** [comment]
Hi tahanjokunimi,

Thanks for checking out dma_pwm and leaving a question.

The behavior that you describe in the first bullet point indicates an incorrectly set pulse width. I'm guessing that you did not update the `config_pwm(int pages, float pulse_width)` function call (found at the beginning of the test script) when changing the frequency to 100 Hz. 

The test script sets pulse width to `LED_PULSE_WIDTH`. This maps to 10e3 us (or 10 ms) and is suitable for the frequency range 0.05 Hz - 10 Hz. If you would like to set a frequency outside this range, you can either calculate a pulse width or use one of the following presets:
1. `DEFAULT_PULSE_WIDTH` : 100 Hz - 20 kHz
2. `SERVO_PULSE_WIDTH` : 50 Hz - 10 kHz
3. `MOTOR_PULSE_WIDTH` : 5 kHz - 1 Mhz
4. `LED_PULSE_WIDTH` : 0.05 Hz - 10 Hz

See [raspberry_pi_dma_pwm.pdf](doc/raspberry_pi_dma_pwm.pdf) page 5 & 6 and ["dma_pwm_pulse_width_calculator.xlsx"](doc/dma_pwm_pulse_width_calculator.xlsx) for a discussion on how to calculate this for yourself.

The behavior described in the second bullet point is something I'm going to look into further so let me get back to you on that.

**Comment by besp9510** [comment]
Hi tahanjokunimi,

I have just pushed a fix for the frequency issue that you discovered. Thank you for bringing it to my attention!
