### ISSUE TITLE
dma_pwm for other than raspberry pi ?

### ISSUE THREAD

**Issue by Renondedju** [besp9510/dma_pwm#3]
I am a complete beginner in the DMA domain, that's why I'm allowing myself to ask for some directions here:
- Would it be possible to use this library with another processor?
- If yes, how hard would it be?

**Here is what I'm trying to achieve:**
I have a Cubietruck *(aka. [Cubieboard](http://cubieboard.org) 3)* with PWM capabilities (processor is an [AllWinner A20](https://www.olimex.com/Products/SOM/A20/_resources/A20-Brief-2013-02-27.pdf)) and I'm looking to drive a WS2812b led strip with it in user-mode. I found [some libraries](https://github.com/jgarff/rpi_ws281x) that achieved it on a raspberry pi already, but they all seem to be hardcoded for the pi's hardware sadly.  

I ended up finding this repo that seemed very promising and I don't mind having to re-implement the led strip's protocol.  
Thank you very much!

**Comment by besp9510** [comment]
Hey Renondeju,

Thanks for checking out dma_pwm!

To answer you questions:
1. I would say the fundamental principles behind the library could be applied to other processors (system on a chip really) that have a DMA controller which can manipulate the state of GPIOs through memory (e.g., a register)
2. Difficulty for implementing this on another SoC would come down to how the DMA Controller functions, how easily GPIO states can be manipulated, and figuring out how to ensure memory isn't allocated in the processor's cache. I recall that last point being the one big hurdle to get this library working and I was able to rely on an existing interface Broadcom created.

I appreciate the explanation for what you're trying to accomplish + the links. I took a quick look through the AllWinner A20 [user's manual](https://data2.manualslib.com/pdf4/84/8325/832448-allwinner/a20.pdf?eb834ac02950869a2551d24706fc6d2a) and the one thing that jumps out to me is that the DMA data request destination register has a list of options that doesn't seem to include the port configuration module (PIO)? This module configures all the ports/GPIOs.

I am not familiar with this SoC so I would have to do more digging to better understand if the DMA controller has access to the port controller and could therefore set and clear GPIO pins to create a PWM signal.

![image](https://user-images.githubusercontent.com/36608012/166415831-f64db094-6a48-4da3-b809-faa16fc5659e.png)

That all being said, I'm curious why you not able to use the A20's built-in PWM functionality to drive the WS2812b LED strip. What's making you to consider generating a PWM signal via DMA for this project? I haven't worked with these LED strips before.

**Comment by Renondedju** [comment]
Hi! Thanks for the quick answer!

If I understood well from the docs you provided with this repo, DMA can drive the PWM module asynchronously from the CPU itself, which would allow me to stay in user-mode without suffering from all the context switches/interrupts that would mess up the timings in the [communication to the led strip](https://voltiq.ru/datasheets/WS2812B_datasheet_EN.pdf).
To be totally honest I could have misunderstood something, again, all of this is fairly new to me...

**Comment by besp9510** [comment]
That's correct. The DMA controller is like an engine the CPU configures, starts, and stops but runs by itself.

I see the A20 has hardware PWM capability through a dedicated register counter. SoCs with hardware PWM output typically rely on a separate controller or hardware logic and clock to produce the signal. Like a DMA controller, they run asynchronously and are just managed by the CPU. Perhaps this will be sufficient for driving the LED strip? A20 offers 16 bit duty cycle and frequency resolution between 24 MHz and 5.8 kHz. I'm seeing this on page 102 of the manual.

![image](https://user-images.githubusercontent.com/36608012/166625884-3d0f9be3-6ec2-4dc7-8d87-9524fcf5e5bb.png)

On the Pi, I am able to stay in user-mode/space by accessing the "mem" character device when mapping physical (register) addresses to a program's virtual memory to manipulate them.
