### ISSUE TITLE
Conflict with ws281x

### ISSUE THREAD

**Issue by sporubcan** [besp9510/dma_pwm#4]
Hello,
I tried to run PWM on GPIO 13 using your library. It worked well.
But wen I start LED rendering using rpi_ws281x (https://github.com/jgarff/rpi_ws281x) on GPIO12, LED is interfered by your PWM. 
Could you please help me?
I assume, both libraries are using some same resources. 

Here is debug output of my test program using dma_pwm:
> 
> Configuring dma_pwm.c
> Setting pulse width to 0.400 us
> Setting number of allocated pages to 16
> Configured dma_pwm.c
> dma_pwm.c configured
> DEBUG logs enabled for dma_pwm.c!
> Initializing dma_pwm.c
> Signal 1 registered with signal handler
> Signal 3 registered with signal handler
> Signal 2 registered with signal handler
> Signal 15 registered with signal handler
> Setting PI board version as 4
> BCM peripheral base physical address = 0xFE000000
> BCM peripheral base bus address = 0x7E000000
> GPSET0 bus address = 0x7E20001C
> GPCLR0 bus address = 0x7E200028
> PWMFIF1 bus address = 0x7E200028
> Setting pulse width to 0.400 us
> Mapped peripherals into virtual memory:
> GPIO base virtual address = 0xb6fda000
> DMA CTL base virtual address = 0xb6fd9000
> PWM CTL base virtual address = 0xb6fd8000
> PWM CLK base virtual address = 0xb6fd7000
> PWM CTL and CM initialized:
> PWM CM Register: PWMDIV = 0x00002000
> PWM CM Register: PWMCTL = 0x00000096
> PWM CTL Register: CTL = 0x00000021
> PWM CTL Register: DMAC = 0x80000F0F
> PWM CTL Register: RNG1 = 0x00000064
> Initialized dma_pwm.c
> Initializing channel 0
> Setting page size to 4096 bytes
> Setting channel 0 selected CB buffer to 1
> Channel 0 initialized with 65536 bytes allocated (x2)
> Channel 0 requested
> PWM signal to be set on channel 0
> Selecting CB buffer 0 for channel 0
> Setting GPIO masks
> GPIO set mask = 0x00002000
> GPIO clear mask = 0x00002000
> Setting PWM signal and CB sequence properties:
> Pulse width = 0.4000 us
> Subcycle = 10 us
> Actual frequency = 104166.6640625 Hz
> Duty cycle resolution = 8.3333311%
> Actual duty cycle = 74.9999771%
> CB sequence "set" number = 9
> CB sequence "clear" number = 3
> CB sequence total number = 14
> Building CB sequence for channel 0 on buffer 0
> Built CB sequence for channel 0 on buffer 0
> Channel 0 PWM signal set
> Channel 0 PWM signal set
> PWM signal frequency: 104166.664 Hz
> PWM signal duty cycle: 75.000%
> Channel 0 to be enabled
> Loading CB sequence from buffer 0
> DMA Channel 0 Register: CONBLK_AD = 0xBEBB7000
> DMA Channel 0 Register: CS = 0x10770009
> Channel 0 enabled
> Channel 0 enabled
> Channel 0 to be disabled
> GPIO BCM pin 13 cleared
> Channel 0 disabled
> Channel 0 disabled
> Channel 0 to be freed
> Channel 0 to be disabled
> GPIO BCM pin 13 cleared
> Channel 0 disabled

**Comment by besp9510** [comment]
Hi Sporubcan,

I see the issue:

![image](https://user-images.githubusercontent.com/36608012/181401542-6aff040e-cf29-46f5-bb17-9619a137787f.png)

ws281x uses DMA channel number 10 by default. dma_pwm also uses channel by 10 (channels 10, 8, 9, 11, 12, 13, 14 in that order based on when a channel is requested), so this is why you are seeing an interference.

Is is possible to adjust the DMA channel ws281x is using?

I originally did not intend dma_pwm to be used with other libraries that utilize DMA channels so this is why the specific DMA channel cannot be requested (at least at this time). Out of curiosity, why do you need both dma_pwm and ws281x  to be running at the same time?

**Comment by sporubcan** [comment]
Hi, I tried also other dma channels, but result was the same. I see the conflict on the different place - your DMA_PWM library uses PWM clock generator, which is used for both native PWM channels... But never mind. In my final application I decided finally not use pwm generator.
